### PR TITLE
Fix #4 Support more Server Sent Events

### LINKED ISSUE #4: Support more Server Sent Events features
Server Sent Events supports a number of features that can't be achieved with this plugin OOTB:

- multiline data
-  comments
- ids
- reconnection time
- multiplexed events on the same EventSource

See here: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

This plugin should expose a way to use these features

### PR DESCRIPTION
**Pull request by sbearcsiro**
- Provide a new type that RxResultSubscriber knows about: `SseResult`
 - `SseResult` and helper methods provide ways of constructing Server Sent Events with comments, ids, retry and multiline data
 - Update example with `SseResult` usage and make example use local copy of plugin.

### CODE REVIEW

**Comment by graemerocher** [comment]
Wow nice contribution. I will review soon. Thanks

**Comment by graemerocher** [comment]
Only thing I would like to change about this pull request is to please remove the dependency on `grails.converters.JSON`. To make it work the same what we can do is make the `JSON` class in core implement the `Writable` interface. That would be a better and cleaner solution.

Can you do that?

**Comment by sbearcsiro** [comment]
@graemerocher sure - would you prefer 

a) `grails.converters.JSON` implement `Writable`; or 
b) the base `Converter` interface extend `Writable` and `AbstractConverter` implement `writeTo` by calling `render`.

Or something else?

**Comment by graemerocher** [comment]
@sbearcsiro The base class `AbstractConverter` would be better, since it isn't as much of a breaking change. Thanks!

**Comment by sbearcsiro** [comment]
@jeffbrown and @graemerocher thanks for merging those PRs, I was unexpectedly out of action last week and I'm just catching up now and came here to remove the `Converters` and found it was done already 👍

**Comment by graemerocher** [comment]
@sbearcsiro thank you for the great PR! I back ported it to RxJava 1.x on the 1.0.x branch too

**Pull request merged**
